language: node_js
sudo: false
node_js:
- 10
- 12
install:
- npm ci
- npm ls
notifications:
  slack:
    secure: FhGLqoiuuRowcEyPmBzfPsYXBsy8Rp+Nm8q7qpG8VrDrqEUfHPkPmLzeBxmW1GWiIlEJTyk2nTLy2Rfgfd+z8HJE/qCBTDL4jauqxfo5GaTa1Dxcgd2ciX/uCc005teTsbRNZ41tvIXfXuVwafKAfXb+mxTWTYrYR39tZw1kHmw=
